### DISCUSSION TITLE
在win7中打开时报错：无法定位程序输入点coincrementmtausage

### DISCUSSION THREAD

**Discussion by Robert-Du0001** [tw93/Pake#802] [Q&A]
在win7中打开时会有这个报错：

![d2ae2b602defc2a87235bdc7052e48f0](https://github.com/user-attachments/assets/b04a4776-761c-4d26-8813-2878948d3f65)

Cargo.toml配置：

```toml
[package]
name = "app"
version = "0.1.0"
description = "🤱🏻 Turn any webpage into a desktop app with Rust."
authors = ["Tw93"]
license = "MIT"
repository = "https://github.com/tw93/Pake"
default-run = "app"
edition = "2021"
rust-version = "1.75"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.2", features = [] }

[dependencies]
serde_json = "1.0.117"
serde = { version = "1.0.202", features = ["derive"] }
tauri = { version = "1.6.6", features = ["api-all", "system-tray", "windows7-compat"] }
tauri-plugin-window-state = { git = "https://github.com/tauri-apps/plugins-workspace", branch = "v1" }
tauri-plugin-oauth = { git = "https://github.com/FabianLars/tauri-plugin-oauth", branch = "main" }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
cargo-bloat = "0.11.1"

[features]
# this feature is used for development builds from development cli
cli-build = []
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
```

编译命令：

```sh
npm run tauri build -- --target i686-pc-windows-msvc
```

但是如果直接使用tauri编译个demo是能正常打开的：

![1c962831fd8844feda95a2ea5d621e62](https://github.com/user-attachments/assets/cdb15aa5-8929-46fe-815f-4966c3a97816)

tauri的demo的配置如下：

```toml
[package]
name = "demo4"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"
rust-version = "1.75"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = ["shell-open", "windows7-compat"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]

```

 有人知道这是怎么回事吗？
